version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
        - PORT=8080
        - DATABASE_URL=postgres://API_USER:API_PASSWORD@POSTGRES_HOST:5432/POSTGRES_DB
        - QUOTATOR_TOKEN=
        - TELEGRAM_TOKEN=
        - UNIPASSAUBOT_TOKEN=
        - DISCORD_TOKEN=
        - REDIS_URL=redis://user:password@host:port
        - MODE=DEBUG or PRODUCTION
    depends_on:
      - postgres
    networks:
      - tasadar
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - tasadar
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api_password
      POSTGRES_DB: api
    volumes:
    - api-postgres:/var/lib/postgresql/data

volumes:
  api-postgres:
    external: false

networks:
  api-test:
    driver: bridge
