version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
        - PORT=8080
        # Append ?sslmode=disable to DATABASE_URL if not using ssl
        - DATABASE_URL=postgres://USER:PASSWORD@ADDRESS:PORT/DB_NAME
        - TELEGRAM_TOKEN=
        - UNIPASSAUBOT_TOKEN=
        - DISCORD_TOKEN=
        - MODE=DEBUG
    networks:
      - tasadar
    volumes:
    - api-data:/data

volumes:
  api-data:
    external: false

networks:
  tasadar:
    driver: bridge
