version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://glyph:awesomePassword@db:5432/glyphDB?sslmode=disable
      - TELEGRAM_TOKEN=
      - UNIPASSAUBOT_TOKEN=
      - DISCORD_TOKEN=
      - MODE=PRODUCTION
    networks:
      - tasadar
    volumes:
      - api-data:/data
    depends_on: 
      - db

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: awesomePassword
      POSTGRES_USER: glyph
      POSTGRES_DB: glyphDB
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - "api-postgres-data:/var/lib/postgresql/"
    networks: ["tasadar"]

volumes:
  api-data:
    external: false
  api-postgres-data:
    external: false

networks:
  tasadar:
    driver: bridge
